# Iris

### Introduction:



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

### Step 2. Import the dataset

In [2]:
pd.read_csv("C:/Python_pandas/iris.csv")

    5.1  3.5  1.4  0.2  Iris-setosa
0   4.9  3.0  1.4  0.2  Iris-setosa
1   4.7  3.2  1.3  0.2  Iris-setosa
2   4.6  3.1  1.5  0.2  Iris-setosa
3     5  3.6  1.4  0.2  Iris-setosa
4   5.4  3.9  1.7  0.4  Iris-setosa
5   4.6  3.4  1.4  0.3  Iris-setosa
6     5  3.4  1.5  0.2  Iris-setosa
7   4.4  2.9  1.4  0.2  Iris-setosa
8   4.9  3.1  1.5  0.1  Iris-setosa
9   5.4  3.7  1.5  0.2  Iris-setosa
10  4.8  3.4  1.6  0.2  Iris-setosa
11  4.8  3.0  1.4  0.1  Iris-setosa
12  4.3  3.0  1.1  0.1  Iris-setosa
13  5.8  4.0  1.2  0.2  Iris-setosa
14  5.7  4.4  1.5  0.4  Iris-setosa
15  5.4  3.9  1.3  0.4  Iris-setosa
16  5.1  3.5  1.4  0.3  Iris-setosa
17  5.7  3.8  1.7  0.3  Iris-setosa
18  5.1  3.8  1.5  0.3  Iris-setosa
19  5.4  3.4  1.7  0.2  Iris-setosa
20  5.1  3.7  1.5  0.4  Iris-setosa
21  4.6  3.6  1.0  0.2  Iris-setosa
22  5.1  3.3  1.7  0.5  Iris-setosa
23  4.8  3.4  1.9  0.2  Iris-setosa
24    5  3.0  1.6  0.2  Iris-setosa
25    5  3.4  1.6  0.4  Iris-setosa
26  5.2  3.5  1.5  0.2  Iris-setosa
27  5.2  3.4  1.4  0.2  Iris-setosa
28  4.7  3.2  1.6  0.2  Iris-setosa
29  4.8  3.1  1.6  0.2  Iris-setosa
30  5.4  3.4  1.5  0.4  Iris-setosa
31  5.2  4.1  1.5  0.1  Iris-setosa
32  5.5  4.2  1.4  0.2  Iris-setosa
33  4.9  3.1  1.5  0.1  Iris-setosa
34    5  3.2  1.2  0.2  Iris-setosa
35  5.5  3.5  1.3  0.2  Iris-setosa
36  4.9  3.1  1.5  0.1  Iris-setosa
37  ...  NaN  NaN  NaN          NaN

### Step 3. Assign it to a variable called iris

In [3]:
iris = pd.read_csv("C:/Python_pandas/iris.csv")

### Step 4. Create columns for the dataset

In [4]:
# 1. sepal_length (in cm)
# 2. sepal_width (in cm)
# 3. petal_length (in cm)
# 4. petal_width (in cm)
# 5. class

iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

In [5]:
iris.head(5)

  sepal_length  sepal_width  petal_length  petal_width        class
0          4.9          3.0           1.4          0.2  Iris-setosa
1          4.7          3.2           1.3          0.2  Iris-setosa
2          4.6          3.1           1.5          0.2  Iris-setosa
3            5          3.6           1.4          0.2  Iris-setosa
4          5.4          3.9           1.7          0.4  Iris-setosa

### Step 5.  Is there any missing value in the dataframe?

In [6]:
iris.isnull()

    sepal_length  sepal_width  petal_length  petal_width  class
0          False        False         False        False  False
1          False        False         False        False  False
2          False        False         False        False  False
3          False        False         False        False  False
4          False        False         False        False  False
5          False        False         False        False  False
6          False        False         False        False  False
7          False        False         False        False  False
8          False        False         False        False  False
9          False        False         False        False  False
10         False        False         False        False  False
11         False        False         False        False  False
12         False        False         False        False  False
13         False        False         False        False  False
14         False        False         False        False  False
15         False        False         False        False  False
16         False        False         False        False  False
17         False        False         False        False  False
18         False        False         False        False  False
19         False        False         False        False  False
20         False        False         False        False  False
21         False        False         False        False  False
22         False        False         False        False  False
23         False        False         False        False  False
24         False        False         False        False  False
25         False        False         False        False  False
26         False        False         False        False  False
27         False        False         False        False  False
28         False        False         False        False  False
29         False        False         False        False  False
30         False        False         False        False  False
31         False        False         False        False  False
32         False        False         False        False  False
33         False        False         False        False  False
34         False        False         False        False  False
35         False        False         False        False  False
36         False        False         False        False  False
37         False         True          True         True   True

In [7]:
iris.isnull().sum()

sepal_length    0
sepal_width     1
petal_length    1
petal_width     1
class           1
dtype: int64

### Step 6.  Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN

In [15]:
iris.iloc[10:30, 2:3]

    petal_length
10           1.6
11           1.4
12           1.1
13           1.2
14           1.5
15           1.3
16           1.4
17           1.7
18           1.5
19           1.7
20           1.5
21           1.0
22           1.7
23           1.9
24           1.6
25           1.6
26           1.5
27           1.4
28           1.6
29           1.6

In [16]:
iris.iloc[10:30, 2:3] = np.NaN

In [17]:
iris

   sepal_length  sepal_width  petal_length  petal_width        class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3             5          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa
5           4.6          3.4           1.4          0.3  Iris-setosa
6             5          3.4           1.5          0.2  Iris-setosa
7           4.4          2.9           1.4          0.2  Iris-setosa
8           4.9          3.1           1.5          0.1  Iris-setosa
9           5.4          3.7           1.5          0.2  Iris-setosa
10          4.8          3.4           NaN          0.2  Iris-setosa
11          4.8          3.0           NaN          0.1  Iris-setosa
12          4.3          3.0           NaN          0.1  Iris-setosa
13          5.8          4.0           NaN          0.2  Iris-setosa
14          5.7          4.4           NaN          0.4  Iris-setosa
15          5.4          3.9           NaN          0.4  Iris-setosa
16          5.1          3.5           NaN          0.3  Iris-setosa
17          5.7          3.8           NaN          0.3  Iris-setosa
18          5.1          3.8           NaN          0.3  Iris-setosa
19          5.4          3.4           NaN          0.2  Iris-setosa
20          5.1          3.7           NaN          0.4  Iris-setosa
21          4.6          3.6           NaN          0.2  Iris-setosa
22          5.1          3.3           NaN          0.5  Iris-setosa
23          4.8          3.4           NaN          0.2  Iris-setosa
24            5          3.0           NaN          0.2  Iris-setosa
25            5          3.4           NaN          0.4  Iris-setosa
26          5.2          3.5           NaN          0.2  Iris-setosa
27          5.2          3.4           NaN          0.2  Iris-setosa
28          4.7          3.2           NaN          0.2  Iris-setosa
29          4.8          3.1           NaN          0.2  Iris-setosa
30          5.4          3.4           1.5          0.4  Iris-setosa
31          5.2          4.1           1.5          0.1  Iris-setosa
32          5.5          4.2           1.4          0.2  Iris-setosa
33          4.9          3.1           1.5          0.1  Iris-setosa
34            5          3.2           1.2          0.2  Iris-setosa
35          5.5          3.5           1.3          0.2  Iris-setosa
36          4.9          3.1           1.5          0.1  Iris-setosa
37          ...          NaN           NaN          NaN          NaN

### Step 7. Good, now lets substitute the NaN values to 1.0

In [19]:
iris.petal_length.fillna(1, inplace= True)

In [20]:
iris

   sepal_length  sepal_width  petal_length  petal_width        class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3             5          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa
5           4.6          3.4           1.4          0.3  Iris-setosa
6             5          3.4           1.5          0.2  Iris-setosa
7           4.4          2.9           1.4          0.2  Iris-setosa
8           4.9          3.1           1.5          0.1  Iris-setosa
9           5.4          3.7           1.5          0.2  Iris-setosa
10          4.8          3.4           1.0          0.2  Iris-setosa
11          4.8          3.0           1.0          0.1  Iris-setosa
12          4.3          3.0           1.0          0.1  Iris-setosa
13          5.8          4.0           1.0          0.2  Iris-setosa
14          5.7          4.4           1.0          0.4  Iris-setosa
15          5.4          3.9           1.0          0.4  Iris-setosa
16          5.1          3.5           1.0          0.3  Iris-setosa
17          5.7          3.8           1.0          0.3  Iris-setosa
18          5.1          3.8           1.0          0.3  Iris-setosa
19          5.4          3.4           1.0          0.2  Iris-setosa
20          5.1          3.7           1.0          0.4  Iris-setosa
21          4.6          3.6           1.0          0.2  Iris-setosa
22          5.1          3.3           1.0          0.5  Iris-setosa
23          4.8          3.4           1.0          0.2  Iris-setosa
24            5          3.0           1.0          0.2  Iris-setosa
25            5          3.4           1.0          0.4  Iris-setosa
26          5.2          3.5           1.0          0.2  Iris-setosa
27          5.2          3.4           1.0          0.2  Iris-setosa
28          4.7          3.2           1.0          0.2  Iris-setosa
29          4.8          3.1           1.0          0.2  Iris-setosa
30          5.4          3.4           1.5          0.4  Iris-setosa
31          5.2          4.1           1.5          0.1  Iris-setosa
32          5.5          4.2           1.4          0.2  Iris-setosa
33          4.9          3.1           1.5          0.1  Iris-setosa
34            5          3.2           1.2          0.2  Iris-setosa
35          5.5          3.5           1.3          0.2  Iris-setosa
36          4.9          3.1           1.5          0.1  Iris-setosa
37          ...          NaN           1.0          NaN          NaN

### Step 8. Now let's delete the column class

In [21]:
del iris['class']

In [22]:
iris

   sepal_length  sepal_width  petal_length  petal_width
0           4.9          3.0           1.4          0.2
1           4.7          3.2           1.3          0.2
2           4.6          3.1           1.5          0.2
3             5          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4
5           4.6          3.4           1.4          0.3
6             5          3.4           1.5          0.2
7           4.4          2.9           1.4          0.2
8           4.9          3.1           1.5          0.1
9           5.4          3.7           1.5          0.2
10          4.8          3.4           1.0          0.2
11          4.8          3.0           1.0          0.1
12          4.3          3.0           1.0          0.1
13          5.8          4.0           1.0          0.2
14          5.7          4.4           1.0          0.4
15          5.4          3.9           1.0          0.4
16          5.1          3.5           1.0          0.3
17          5.7          3.8           1.0          0.3
18          5.1          3.8           1.0          0.3
19          5.4          3.4           1.0          0.2
20          5.1          3.7           1.0          0.4
21          4.6          3.6           1.0          0.2
22          5.1          3.3           1.0          0.5
23          4.8          3.4           1.0          0.2
24            5          3.0           1.0          0.2
25            5          3.4           1.0          0.4
26          5.2          3.5           1.0          0.2
27          5.2          3.4           1.0          0.2
28          4.7          3.2           1.0          0.2
29          4.8          3.1           1.0          0.2
30          5.4          3.4           1.5          0.4
31          5.2          4.1           1.5          0.1
32          5.5          4.2           1.4          0.2
33          4.9          3.1           1.5          0.1
34            5          3.2           1.2          0.2
35          5.5          3.5           1.3          0.2
36          4.9          3.1           1.5          0.1
37          ...          NaN           1.0          NaN

### Step 9.  Set the first 3 rows as NaN

In [23]:
iris.iloc[0:3, :] = np.nan

In [24]:
iris

   sepal_length  sepal_width  petal_length  petal_width
0           NaN          NaN           NaN          NaN
1           NaN          NaN           NaN          NaN
2           NaN          NaN           NaN          NaN
3             5          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4
5           4.6          3.4           1.4          0.3
6             5          3.4           1.5          0.2
7           4.4          2.9           1.4          0.2
8           4.9          3.1           1.5          0.1
9           5.4          3.7           1.5          0.2
10          4.8          3.4           1.0          0.2
11          4.8          3.0           1.0          0.1
12          4.3          3.0           1.0          0.1
13          5.8          4.0           1.0          0.2
14          5.7          4.4           1.0          0.4
15          5.4          3.9           1.0          0.4
16          5.1          3.5           1.0          0.3
17          5.7          3.8           1.0          0.3
18          5.1          3.8           1.0          0.3
19          5.4          3.4           1.0          0.2
20          5.1          3.7           1.0          0.4
21          4.6          3.6           1.0          0.2
22          5.1          3.3           1.0          0.5
23          4.8          3.4           1.0          0.2
24            5          3.0           1.0          0.2
25            5          3.4           1.0          0.4
26          5.2          3.5           1.0          0.2
27          5.2          3.4           1.0          0.2
28          4.7          3.2           1.0          0.2
29          4.8          3.1           1.0          0.2
30          5.4          3.4           1.5          0.4
31          5.2          4.1           1.5          0.1
32          5.5          4.2           1.4          0.2
33          4.9          3.1           1.5          0.1
34            5          3.2           1.2          0.2
35          5.5          3.5           1.3          0.2
36          4.9          3.1           1.5          0.1
37          ...          NaN           1.0          NaN

### Step 10.  Delete the rows that have NaN

In [25]:
iris = iris.dropna(how='any')

In [26]:
iris

   sepal_length  sepal_width  petal_length  petal_width
3             5          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4
5           4.6          3.4           1.4          0.3
6             5          3.4           1.5          0.2
7           4.4          2.9           1.4          0.2
8           4.9          3.1           1.5          0.1
9           5.4          3.7           1.5          0.2
10          4.8          3.4           1.0          0.2
11          4.8          3.0           1.0          0.1
12          4.3          3.0           1.0          0.1
13          5.8          4.0           1.0          0.2
14          5.7          4.4           1.0          0.4
15          5.4          3.9           1.0          0.4
16          5.1          3.5           1.0          0.3
17          5.7          3.8           1.0          0.3
18          5.1          3.8           1.0          0.3
19          5.4          3.4           1.0          0.2
20          5.1          3.7           1.0          0.4
21          4.6          3.6           1.0          0.2
22          5.1          3.3           1.0          0.5
23          4.8          3.4           1.0          0.2
24            5          3.0           1.0          0.2
25            5          3.4           1.0          0.4
26          5.2          3.5           1.0          0.2
27          5.2          3.4           1.0          0.2
28          4.7          3.2           1.0          0.2
29          4.8          3.1           1.0          0.2
30          5.4          3.4           1.5          0.4
31          5.2          4.1           1.5          0.1
32          5.5          4.2           1.4          0.2
33          4.9          3.1           1.5          0.1
34            5          3.2           1.2          0.2
35          5.5          3.5           1.3          0.2
36          4.9          3.1           1.5          0.1

### Step 11. Reset the index so it begins with 0 again

In [29]:
iris.reset_index(drop= True)

   sepal_length  sepal_width  petal_length  petal_width
0             5          3.6           1.4          0.2
1           5.4          3.9           1.7          0.4
2           4.6          3.4           1.4          0.3
3             5          3.4           1.5          0.2
4           4.4          2.9           1.4          0.2
5           4.9          3.1           1.5          0.1
6           5.4          3.7           1.5          0.2
7           4.8          3.4           1.0          0.2
8           4.8          3.0           1.0          0.1
9           4.3          3.0           1.0          0.1
10          5.8          4.0           1.0          0.2
11          5.7          4.4           1.0          0.4
12          5.4          3.9           1.0          0.4
13          5.1          3.5           1.0          0.3
14          5.7          3.8           1.0          0.3
15          5.1          3.8           1.0          0.3
16          5.4          3.4           1.0          0.2
17          5.1          3.7           1.0          0.4
18          4.6          3.6           1.0          0.2
19          5.1          3.3           1.0          0.5
20          4.8          3.4           1.0          0.2
21            5          3.0           1.0          0.2
22            5          3.4           1.0          0.4
23          5.2          3.5           1.0          0.2
24          5.2          3.4           1.0          0.2
25          4.7          3.2           1.0          0.2
26          4.8          3.1           1.0          0.2
27          5.4          3.4           1.5          0.4
28          5.2          4.1           1.5          0.1
29          5.5          4.2           1.4          0.2
30          4.9          3.1           1.5          0.1
31            5          3.2           1.2          0.2
32          5.5          3.5           1.3          0.2
33          4.9          3.1           1.5          0.1

### BONUS: Create your own question and answer it.